// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sln.Payment.Data;

#nullable disable

namespace Sln.Payment.Migrator.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    partial class SchedulerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sln.Payment.Data.Entities.JobInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("data");

                    b.Property<int>("JobEvent")
                        .HasColumnType("int")
                        .HasColumnName("job_event");

                    b.Property<string>("JobId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("job_id");

                    b.Property<int?>("JobStatus")
                        .HasColumnType("int")
                        .HasColumnName("job_status");

                    b.Property<string>("JobType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("job_type");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("object_id");

                    b.Property<DateTime?>("SendTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("send_time");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_job_info");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_job_info_object_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_job_info_transaction_id");

                    b.ToTable("job_info", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
